version: '3.8'
services:
  nginx:
    image: nginx:1.17.4-alpine
    ports:
      - 8888:80
    depends_on:
      - php
      - db
    volumes:
      - .:/application:cached
      - ./docker/config/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

  php:
    build: 
      context: ./docker
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - .:/application:cached
      - ./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    depends_on:
      - db
      - redis
    environment:
      - DB_PORT=${DB_PORT:-3306}
      - DB_HOST=${DB_HOST:-db}
      - DB_USERNAME=${DB_USERNAME:-root}
      - DB_PASSWORD=${DB_PASSWORD:-123456789}
      - DB_NAME=${DB_DATABASE:-app_db}
    networks:
      - app-network

  db:
    image: mariadb:10.5.8
    container_name: db
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=app_db
      - MYSQL_ROOT_PASSWORD=123456789
      - MYSQL_PASSWORD=123456789
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p123456789"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - app-network

  redis:
    image: redis:5.0.6-alpine
    ports:
      - "6382:6379"
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8082:80
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=123456789
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data: