services:
  php-env:
    build: .
    volumes:
      - ./src:/var/www/html
      - ./my-php-app.conf:/etc/apache2/sites-available/my-php-app.conf
    ports:
      - "9000:80"
    environment:
      DB_CONNECTION: mysql
      DB_HOST: database-1.c1vao1bbmxs8.us-west-2.rds.amazonaws.com
      DB_PORT: 3306
      DB_DATABASE: dvd_web
      DB_USERNAME: admin
      DB_PASSWORD: 0333342584
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
