version: '3.8'

services:
  nginx:
    image: nginx:1.17.4-alpine
    ports:
      - 8888:80
    volumes:
      - ./docker/config/default.conf:/etc/nginx/conf.d/default.conf
      - nginx_data:/etc/nginx   # Volume to store active_green marker
    depends_on:
      - php-blue
      - php-green

  php-blue:
    build: ./docker
    image: randytuan098/php:blue
    volumes:
      - ./src:/application
      - ./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    environment:
      - APP_COLOR=blue
      - DB_HOST=db
      - DB_USERNAME=root
      - DB_PASS=123456789
      - DB_NAME=app_db
    expose:
      - "9000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/health.php"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  php-green:
    build: ./docker
    image: randytuan098/php:green
    volumes:
      - ./src:/application
      - ./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    environment:
      - APP_COLOR=green
      - DB_HOST=db
      - DB_USERNAME=root
      - DB_PASS=123456789
      - DB_NAME=app_db
    expose:
      - "9000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/health.php"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  db:
    image: mariadb:10.5.8
    container_name: db
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=app_db
      - MYSQL_ROOT_PASSWORD=123456789
      - MYSQL_PASSWORD=123456789

  redis:
    image: redis:5.0.6-alpine
    ports:
      - "6382:6379"

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8082:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
    depends_on:
      - db

volumes:
  db_data:
  nginx_data:
