name: Blue/Green Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Determine deployment target (blue/green)
        id: get-env
        run: |
          CURRENT=$(cat active_env.txt || echo "green")
          if [ "$CURRENT" = "green" ]; then
            echo "TARGET=blue" >> $GITHUB_ENV
          else
            echo "TARGET=green" >> $GITHUB_ENV
          fi

      - name: Update active_env.txt
        run: echo "${{ env.TARGET }}" > active_env.txt

      - name: Build new app container
        run: docker-compose build php-${{ env.TARGET }}

      - name: Start updated services
        run: docker-compose up -d php-${{ env.TARGET }} nginx

      - name: Cleanup old service
        run: docker-compose stop php-${{ env.CURRENT }}
