name: Build and Deploy webnetflopt

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, exif, pcntl, pdo_mysql, zip, gd
          coverage: xdebug
      
      # Skip creating .env as we're using the existing one in the repository
      
      - name: Install Composer dependencies
        run: composer install --no-progress --no-interaction --prefer-dist
      
      # Skip key generation as the .env already has a key set
        # run: php artisan key:generate
      
      - name: Set directory permissions
        run: |
          chmod -R 777 storage bootstrap/cache
      
      - name: Run tests
        run: php artisan test
      
      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Set up Docker Buildx
        if: github.event_name != 'pull_request'
        uses: docker/setup-buildx-action@v2
      
      - name: Build and push PHP Docker image
        if: github.event_name != 'pull_request'
        uses: docker/build-push-action@v4
        with:
          context: ./docker
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/webnetflopt-php:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/webnetflopt-php:${{ github.sha }}
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/webnetflopt-php:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/webnetflopt-php:buildcache,mode=max
