name: Laravel Docker CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-docker-tests:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:dind

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Build and run containers
      run: docker compose up -d --build

    - name: Wait for services to be healthy
      run: sleep 20

    - name: Run Laravel migrations
      run: docker compose exec php php artisan migrate --force

    - name: Run Laravel tests
      run: docker compose exec php php artisan test

    - name: Stop containers
      if: always()
      run: docker compose down
