name: Build and Push Docker Images

on:
  push:
    branches:
      - main  # or 'master', depending on your repo
  workflow_dispatch:  # Allow manual trigger

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ env.DOCKERHUB_USERNAME }}
        password: ${{ env.DOCKERHUB_TOKEN }}

    - name: Build and push nginx image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./docker-compose.yml
        push: true
        tags: ${{ env.DOCKERHUB_USERNAME }}/nginx:latest

    - name: Build and push php image
      uses: docker/build-push-action@v5
      with:
        context: ./docker
        push: true
        tags: ${{ env.DOCKERHUB_USERNAME }}/php:latest

    - name: Push mariadb (db) and redis
      run: |
        docker pull mariadb:10.5.8
        docker pull redis:5.0.6-alpine
        docker tag mariadb:10.5.8 $DOCKERHUB_USERNAME/mariadb:10.5.8
        docker tag redis:5.0.6-alpine $DOCKERHUB_USERNAME/redis:5.0.6-alpine
        docker push $DOCKERHUB_USERNAME/mariadb:10.5.8
        docker push $DOCKERHUB_USERNAME/redis:5.0.6-alpine

    - name: Push phpmyadmin
      run: |
        docker pull phpmyadmin
        docker tag phpmyadmin $DOCKERHUB_USERNAME/phpmyadmin:latest
        docker push $DOCKERHUB_USERNAME/phpmyadmin:latest
